# Generated by Django 4.2.7 on 2023-12-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
