from .index import *
from .avaliacao import *
from .recomendar import *
from .comentario import *
from .perfil import *
from .seguir import *
from .recomendacao import *
from .settings import *
from .cadastro import *
from .login import *
from .logout import *
from .home import *
from .buscar import *
from .notification import *
