# Generated by Django 4.2.7 on 2023-12-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='conhecimento.png', upload_to='post_images'),
        ),
    ]
